from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from qa_pipeline.core.runtime_logger import log_event
from qa_pipeline.core.paths import REPORTS_DIR


def _now() -> str:
    return datetime.now().isoformat(timespec='seconds')


def _safe_slug(value: Any, default: str = 'astraheal') -> str:
    text = str(value or default).strip()
    text = re.sub(r'[^A-Za-z0-9_.:\\[\]/@&\-]+', '_', text)
    return text[:180] or default


def _quote_arg(value: Any) -> str:
    text = str(value if value is not None else '')
    return subprocess.list2cmdline([text]) if os.name == 'nt' else shlex_quote(text)


def shlex_quote(text: str) -> str:
    import shlex
    return shlex.quote(text)


def browserstack_credentials_status() -> dict[str, Any]:
    user = os.environ.get('BROWSERSTACK_USERNAME') or os.environ.get('BROWSERSTACK_USER') or ''
    key = os.environ.get('BROWSERSTACK_ACCESS_KEY') or os.environ.get('BROWSERSTACK_KEY') or ''
    return {
        'username_present': bool(user.strip()),
        'access_key_present': bool(key.strip()),
        'ok': bool(user.strip() and key.strip()),
        'username_env': 'BROWSERSTACK_USERNAME' if os.environ.get('BROWSERSTACK_USERNAME') else ('BROWSERSTACK_USER' if os.environ.get('BROWSERSTACK_USER') else ''),
        'access_key_env': 'BROWSERSTACK_ACCESS_KEY' if os.environ.get('BROWSERSTACK_ACCESS_KEY') else ('BROWSERSTACK_KEY' if os.environ.get('BROWSERSTACK_KEY') else ''),
    }


def check_browserstack_readiness(framework_path: str = '') -> dict[str, Any]:
    root = Path(framework_path).expanduser().resolve() if framework_path else None
    node = shutil.which('node')
    npm = shutil.which('npm') or shutil.which('npm.cmd')
    npx = shutil.which('npx') or shutil.which('npx.cmd')
    creds = browserstack_credentials_status()
    package_json = root / 'package.json' if root else None
    package_ok = bool(package_json and package_json.exists())
    sdk_declared = False
    if package_ok:
        try:
            pkg = json.loads(package_json.read_text(encoding='utf-8', errors='replace'))
            deps = {**(pkg.get('dependencies') or {}), **(pkg.get('devDependencies') or {})}
            sdk_declared = 'browserstack-node-sdk' in deps
        except Exception:
            sdk_declared = False
    ok = bool(creds.get('ok') and node and npm and npx and package_ok)
    result = {
        'ok': ok,
        'framework_path': str(root) if root else '',
        'node_found': bool(node),
        'npm_found': bool(npm),
        'npx_found': bool(npx),
        'package_json_found': package_ok,
        'browserstack_node_sdk_declared': sdk_declared,
        'credentials': creds,
        'message': 'BrowserStack execution is ready.' if ok else 'BrowserStack execution needs credentials, Node/npm/npx, and a valid Playwright framework package.json.',
        'safe_note': 'AstraHeal AI/RCA/self-healing remains on this VM. BrowserStack is used only as the execution browser grid.',
    }
    log_event('browserstack_execution', result['message'], status='ok' if ok else 'warning', progress=100, details=result)
    return result


def write_browserstack_config(
    framework_root: Path,
    run_id: str,
    shard_id: str,
    selected_tests: list[str],
    browser: str = 'chrome',
    browser_version: str = 'latest',
    os_name: str = 'Windows',
    os_version: str = '11',
    local_testing: bool = True,
    local_identifier: str = '',
    project_name: str = 'AstraHeal AI',
    build_name: str = '',
    session_name: str = '',
) -> Path:
    cfg_dir = framework_root / '.astraheal' / 'browserstack' / run_id / shard_id
    cfg_dir.mkdir(parents=True, exist_ok=True)
    local_id = local_identifier or f'astraheal-{run_id}'
    build = _safe_slug(build_name or f'AstraHeal-{run_id}')
    session = _safe_slug(session_name or f'{shard_id}-{len(selected_tests)}-tests')
    # BrowserStack SDK accepts BROWSERSTACK_CONFIG_FILE; credentials can stay in env.
    # We intentionally write into .astraheal instead of mutating the user's root browserstack.yml.
    yml = f"""# Generated by AstraHeal AI. Do not commit credentials here.
# Source of truth stays in the selected external Playwright framework; AI/RCA stays on the VM.
userName: ${{BROWSERSTACK_USERNAME}}
accessKey: ${{BROWSERSTACK_ACCESS_KEY}}
framework: playwright
projectName: {project_name}
buildName: {build}
buildIdentifier: {run_id}
sessionName: {session}
browserstackLocal: {str(bool(local_testing)).lower()}
"""
    if local_testing:
        yml += f"browserStackLocalOptions:\n  localIdentifier: {local_id}\n  forceLocal: true\n"
    yml += f"""debug: true
networkLogs: true
consoleLogs: verbose
playwrightLogs: true
platforms:
  - os: {os_name}
    osVersion: '{os_version}'
    browserName: {browser}
    browserVersion: {browser_version}
playwrightConfigOptions:
  timeout: 30000
  expect:
    timeout: 5000
  use:
    actionTimeout: 30000
    navigationTimeout: 30000
"""
    path = cfg_dir / 'browserstack.yml'
    path.write_text(yml, encoding='utf-8')
    return path


def build_browserstack_command(
    framework_root: Path,
    config_file: Path,
    tests: list[str],
    headed: bool = False,
    output_dir: Path | None = None,
) -> str:
    quoted_tests = ' '.join(_quote_arg(t) for t in tests if str(t).strip())
    base = 'npx --yes browserstack-node-sdk playwright test'
    if quoted_tests:
        base += ' ' + quoted_tests
    base += ' --workers=1 --reporter=line,json,html --timeout=30000 --retries=1'
    if output_dir:
        base += ' --output=' + _quote_arg(output_dir)
    # BrowserStack execution is remote; headed flag is retained as metadata only.
    if os.name == 'nt':
        return 'set BROWSERSTACK_CONFIG_FILE=' + subprocess.list2cmdline([str(config_file)]) + '&& ' + base
    return 'BROWSERSTACK_CONFIG_FILE=' + shlex_quote(str(config_file)) + ' ' + base


def write_browserstack_report_index(framework_root: Path, summary: dict[str, Any]) -> dict[str, Any]:
    reports = framework_root / '.aiqa-history' / 'reports'
    reports.mkdir(parents=True, exist_ok=True)
    central_reports = REPORTS_DIR / 'existing-framework'
    central_reports.mkdir(parents=True, exist_ok=True)
    rows = []
    for sr in summary.get('shard_results') or []:
        sid = sr.get('shard_id') or ''
        status = sr.get('status') or 'unknown'
        dashboard = sr.get('browserstack_dashboard_note') or 'Open BrowserStack Automate dashboard using project/build name.'
        rows.append(f"<tr><td>{sid}</td><td>{status}</td><td>{sr.get('browser')}</td><td>{len(sr.get('tests') or [])}</td><td><code>{sr.get('browserstack_config') or ''}</code></td><td><code>{sr.get('html_report') or ''}</code></td><td>{dashboard}</td></tr>")
    body = f"""<!doctype html><html><head><meta charset='utf-8'/><title>AstraHeal BrowserStack Execution Report</title>
<style>body{{font-family:Segoe UI,Arial,sans-serif;margin:24px;background:#f8fafc;color:#0f172a}}table{{width:100%;border-collapse:collapse;background:white}}th,td{{border:1px solid #cbd5e1;padding:8px;vertical-align:top}}th{{background:#1e293b;color:white}}code{{background:#0f172a;color:#dbeafe;padding:2px 5px;border-radius:5px}}</style></head><body>
<h1>AstraHeal BrowserStack Execution Report</h1>
<p><b>Run ID:</b> {summary.get('run_id')}<br/><b>Framework:</b> {framework_root}<br/><b>Scope:</b> BrowserStack is execution only. AI/RCA/self-healing/history remain on this VM.</p>
<p><b>Summary:</b> {summary.get('message') or ''}</p>
<table><thead><tr><th>Shard</th><th>Status</th><th>BrowserStack browser</th><th>Targets</th><th>Generated config</th><th>Local HTML artifact</th><th>BrowserStack dashboard</th></tr></thead><tbody>{''.join(rows) or '<tr><td colspan="7">No BrowserStack shards recorded.</td></tr>'}</tbody></table>
</body></html>"""
    local_file = reports / 'browserstack-execution-report.html'
    central_file = central_reports / 'browserstack-execution-report.html'
    local_file.write_text(body, encoding='utf-8')
    central_file.write_text(body, encoding='utf-8')
    return {'ok': True, 'framework_browserstack_report': str(local_file), 'central_browserstack_report': str(central_file), 'browserstack_report_url': '/artifacts/reports/existing-framework/browserstack-execution-report.html'}
