from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
from pathlib import Path
from typing import Any


CODE_EXTENSIONS = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".json")


def strip_jsonc_comments(text: str) -> str:
    """Strip JSONC comments while preserving quoted strings."""
    out: list[str] = []
    i = 0
    n = len(text or "")
    in_string = False
    quote = ""
    escape = False
    while i < n:
        ch = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if in_string:
            out.append(ch)
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == quote:
                in_string = False
                quote = ""
            i += 1
            continue
        if ch in {"'", '"'}:
            # tsconfig/jsonc normally uses double quotes, but single quotes are
            # harmless to preserve until json.loads rejects them as invalid JSON.
            in_string = True
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "/":
            while i < n and text[i] not in "\r\n":
                i += 1
            out.append("\n")
            continue
        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                out.append("\n" if text[i] in "\r\n" else " ")
                i += 1
            i += 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def load_jsonc(path: Path) -> dict[str, Any]:
    try:
        raw = Path(path).read_text(encoding="utf-8", errors="replace")
        text = strip_jsonc_comments(raw)
        text = re.sub(r",\s*([}\]])", r"\1", text)
        data = json.loads(text)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _normalize_rel(value: Any) -> str:
    return str(value or "").replace("\\", "/").strip().strip("/")


def tsconfig_alias_summary(root: Path) -> dict[str, Any]:
    """Read tsconfig/jsconfig path-alias metadata with JSONC support."""
    root = Path(root).expanduser().resolve()
    candidates = [root / "tsconfig.json", root / "jsconfig.json"]
    for cfg in candidates:
        data = load_jsonc(cfg)
        compiler = (data.get("compilerOptions") or {}) if isinstance(data, dict) else {}
        paths = compiler.get("paths") or {}
        if paths or compiler.get("baseUrl"):
            normalized: dict[str, list[str]] = {}
            for key, values in (paths or {}).items():
                vals = values if isinstance(values, list) else [values]
                normalized[str(key)] = [_normalize_rel(v) for v in vals if str(v or "").strip()]
            return {
                "ok": True,
                "config_file": str(cfg),
                "config_rel": cfg.name,
                "base_url": _normalize_rel(compiler.get("baseUrl") or ".") or ".",
                "paths": normalized,
                "alias_count": len(normalized),
                "message": f"TypeScript path aliases loaded from {cfg.name}.",
            }
    return {"ok": False, "config_file": "", "config_rel": "", "base_url": ".", "paths": {}, "alias_count": 0, "message": "No tsconfig/jsconfig path aliases detected."}


def ensure_node_tsconfig_alias_register(root: Path, output_dir: Path | None = None) -> Path | None:
    """Create a small Node require hook for tsconfig path aliases.

    The hook is written under reports/.astraheal generated artifacts, not into the
    user's source folders. It is intentionally dependency-free so restricted VDI/VM
    environments do not need tsconfig-paths installed just to run existing tests.
    """
    root = Path(root).expanduser().resolve()
    summary = tsconfig_alias_summary(root)
    if not summary.get("alias_count"):
        return None
    out_dir = Path(output_dir or (root / "reports" / "existing-framework"))
    out_dir.mkdir(parents=True, exist_ok=True)
    hook = out_dir / ".astraheal-tsconfig-paths-register.cjs"
    payload = {
        "root": str(root),
        "baseUrl": summary.get("base_url") or ".",
        "paths": summary.get("paths") or {},
        "extensions": list(CODE_EXTENSIONS),
    }
    hook.write_text(
        "// Generated by AstraHeal AI. Runtime-only tsconfig path alias resolver; do not commit.\n"
        "(function(){\n"
        "  const fs = require('fs');\n"
        "  const path = require('path');\n"
        "  const Module = require('module');\n"
        f"  const cfg = {json.dumps(payload, ensure_ascii=False)};\n"
        "  const root = cfg.root || process.cwd();\n"
        "  const baseRoot = path.resolve(root, cfg.baseUrl || '.');\n"
        "  const exts = cfg.extensions || ['.ts','.tsx','.js','.jsx','.mjs','.cjs','.json'];\n"
        "  function existingFile(p){ try { return fs.existsSync(p) && fs.statSync(p).isFile(); } catch(e){ return false; } }\n"
        "  function existingDir(p){ try { return fs.existsSync(p) && fs.statSync(p).isDirectory(); } catch(e){ return false; } }\n"
        "  function materialize(base){\n"
        "    const out = [base];\n"
        "    const ext = path.extname(base).toLowerCase();\n"
        "    if (!ext || !exts.includes(ext)) { for (const ext of exts) out.push(base + ext); for (const name of ['index.ts','index.tsx','index.js','index.jsx','index.mjs','index.cjs']) out.push(path.join(base, name)); }\n"
        "    for (const p of out) if (existingFile(p)) return p;\n"
        "    return '';\n"
        "  }\n"
        "  function patternMatch(key, request){\n"
        "    const star = key.indexOf('*');\n"
        "    if (star < 0) return key === request ? [''] : null;\n"
        "    const prefix = key.slice(0, star);\n"
        "    const suffix = key.slice(star + 1);\n"
        "    if (!request.startsWith(prefix) || !request.endsWith(suffix)) return null;\n"
        "    return [request.slice(prefix.length, request.length - suffix.length)];\n"
        "  }\n"
        "  function resolveAlias(request){\n"
        "    for (const [key, values] of Object.entries(cfg.paths || {})) {\n"
        "      const match = patternMatch(key, request);\n"
        "      if (!match) continue;\n"
        "      for (const target of values || []) {\n"
        "        const rel = String(target).replace('*', match[0] || '');\n"
        "        const found = materialize(path.resolve(baseRoot, rel));\n"
        "        if (found) return found;\n"
        "      }\n"
        "    }\n"
        "    if (request.startsWith('@/')) { const found = materialize(path.resolve(baseRoot, request.slice(2))); if (found) return found; }\n"
        "    if (request.startsWith('~/')) { const found = materialize(path.resolve(baseRoot, request.slice(2))); if (found) return found; }\n"
        "    return '';\n"
        "  }\n"
        "  const original = Module._resolveFilename;\n"
        "  Module._resolveFilename = function(request, parent, isMain, options){\n"
        "    try {\n"
        "      if (typeof request === 'string' && (request.startsWith('@') || request.startsWith('~/') || request.startsWith('#'))) {\n"
        "        const found = resolveAlias(request);\n"
        "        if (found) return found;\n"
        "      }\n"
        "    } catch(e) {}\n"
        "    return original.call(this, request, parent, isMain, options);\n"
        "  };\n"
        "})();\n",
        encoding="utf-8",
    )
    return hook


def _node_options_require(register: Path) -> str:
    path_text = str(Path(register).resolve())
    if os.name == "nt":
        return "--require " + subprocess.list2cmdline([path_text])
    return "--require " + shlex.quote(path_text)


def merge_node_options(existing: str, register: Path) -> str:
    req = _node_options_require(register)
    existing = str(existing or "").strip()
    if str(register) in existing:
        return existing
    return (existing + " " + req).strip() if existing else req


def runtime_env_for_tsconfig_aliases(root: Path, output_dir: Path | None = None, base_env: dict[str, str] | None = None) -> dict[str, str]:
    register = ensure_node_tsconfig_alias_register(root, output_dir=output_dir)
    if not register:
        return {}
    existing = (base_env or os.environ).get("NODE_OPTIONS", "")
    return {
        "ASTRAHEAL_FRAMEWORK_ROOT": str(Path(root).expanduser().resolve()),
        "ASTRAHEAL_TSCONFIG_ALIAS_REGISTER": str(register),
        "NODE_OPTIONS": merge_node_options(existing, register),
    }
