from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any
import json
import os
import shutil
import subprocess
import time
import re

from qa_pipeline.core.commands import resolve_command, run_command
from qa_pipeline.core.paths import GENERATED_PLAYWRIGHT_DIR, REPO_ROOT, REPORTS_DIR
from qa_pipeline.core.project_config import load_project_config
from qa_pipeline.core.runtime_logger import log_event
from qa_pipeline.core.url_guard import normalize_base_url
from qa_pipeline.mcp.playwright_mcp import run_playwright_test, mcp_status


def execute_feature(feature: str = 'login', project: str = 'chromium', use_mcp: bool = True, headed: bool = False, base_url: str = '') -> dict:
    log_event('playwright_execution', f'Starting single-spec Playwright execution for {feature}', progress=15, feature=feature, details={'headed': headed, 'project': project})
    result = run_playwright_test(feature=feature, project=project, use_mcp_context=use_mcp, headed=headed, base_url=base_url)
    log_event('playwright_execution', f"Single-spec Playwright execution {'passed' if result.get('ok') else 'completed with issue'} for {feature}", status='done' if result.get('ok') else 'warning', progress=100, feature=feature, details={'ok': result.get('ok')})
    return result


def _feature_spec_arg(feature: str) -> str:
    feature = (feature or '').strip().lower()
    if feature in {'all', '*', 'suite'}:
        return 'tests/generated'
    return f'tests/generated/{feature}.spec.ts'


def _target_args(feature: str = 'all', features: list[str] | None = None) -> list[str]:
    clean_features = [str(f).strip().lower() for f in (features or []) if str(f).strip()]
    if clean_features:
        return [f'tests/generated/{f}.spec.ts' for f in clean_features]
    return [_feature_spec_arg(feature)]


def _playwright_bin_exists() -> bool:
    if (GENERATED_PLAYWRIGHT_DIR / 'node_modules' / '@playwright' / 'test').exists():
        return True
    if (GENERATED_PLAYWRIGHT_DIR / 'node_modules' / '.bin' / 'playwright').exists():
        return True
    if (GENERATED_PLAYWRIGHT_DIR / 'node_modules' / '.bin' / 'playwright.cmd').exists():
        return True
    return False


def _write_fallback_playwright_html(title: str, details: dict[str, Any]) -> None:
    """Always create a readable report page, even if Playwright failed before producing HTML."""
    html_dir = REPORTS_DIR / 'html'
    html_dir.mkdir(parents=True, exist_ok=True)
    body = json.dumps(details, indent=2, ensure_ascii=False)
    (html_dir / 'index.html').write_text(f"""<!doctype html>
<html><head><meta charset=\"utf-8\"/><title>{title}</title>
<style>
body{{font-family:Arial,sans-serif;margin:24px;background:#f8fafc;color:#111827}}
.card{{background:white;border:1px solid #dbe3ef;border-radius:12px;padding:18px;margin:14px 0;box-shadow:0 1px 2px #0001}}
pre{{white-space:pre-wrap;background:#111827;color:#d1fae5;padding:16px;border-radius:10px;overflow:auto}}
.badge{{display:inline-block;padding:4px 9px;border-radius:999px;background:#fee2e2;color:#991b1b;font-weight:700}}
</style></head><body>
<h1>{title}</h1>
<div class=\"card\"><span class=\"badge\">Playwright did not generate a native HTML report</span>
<p>This fallback report was generated by the AI QA Pipeline because execution stopped before Playwright produced <code>reports/html/index.html</code>.</p></div>
<div class=\"card\"><h2>Execution details</h2><pre>{body}</pre></div>
</body></html>""", encoding='utf-8')


def ensure_playwright_runtime(auto_install: bool = True) -> dict[str, Any]:
    """Validate/install the local generated-playwright runtime before execution."""
    started = time.time()
    log_event('playwright_execution', 'Runtime preflight started: checking npm/npx and local Playwright dependencies', progress=12, details={'auto_install': auto_install})
    status: dict[str, Any] = {
        'ok': False,
        'stage': 'playwright_runtime_preflight',
        'generated_playwright_dir': str(GENERATED_PLAYWRIGHT_DIR),
        'auto_install': auto_install,
        'npm_available': bool(resolve_command('npm')),
        'npx_available': bool(resolve_command('npx')),
        'installed_before': _playwright_bin_exists(),
        'steps': [],
    }
    if not status['npm_available']:
        status['error'] = 'npm not found. Install Node.js LTS with npm and reopen the terminal/GUI.'
        log_event('playwright_execution', status['error'], status='error', progress=13)
        _write_fallback_playwright_html('Playwright runtime preflight failed', status)
        return status
    if not status['npx_available']:
        status['error'] = 'npx not found. Install Node.js LTS with npm/npx and reopen the terminal/GUI.'
        log_event('playwright_execution', status['error'], status='error', progress=13)
        _write_fallback_playwright_html('Playwright runtime preflight failed', status)
        return status
    if not (GENERATED_PLAYWRIGHT_DIR / 'package.json').exists():
        status['error'] = 'generated-playwright/package.json not found. The Playwright framework folder is incomplete.'
        log_event('playwright_execution', status['error'], status='error', progress=13)
        _write_fallback_playwright_html('Playwright runtime preflight failed', status)
        return status

    if not _playwright_bin_exists():
        if not auto_install:
            status['error'] = 'Playwright npm dependencies are missing. Run npm install inside generated-playwright.'
            log_event('playwright_execution', status['error'], status='error', progress=14)
            _write_fallback_playwright_html('Playwright runtime preflight failed', status)
            return status
        log_event('playwright_execution', 'Playwright npm dependencies are missing. Running npm install inside generated-playwright.', progress=15)
        install = run_command(['npm', 'install', '--registry=https://registry.npmjs.org/'], cwd=GENERATED_PLAYWRIGHT_DIR, timeout=1200)
        status['steps'].append({'name': 'npm_install', 'ok': install.ok, 'returncode': install.returncode, 'command': install.command, 'stdout': install.stdout[-4000:], 'stderr': install.stderr[-4000:], 'error': install.error})
        if not install.ok:
            status['error'] = 'npm install failed. Playwright cannot execute until generated-playwright dependencies are installed.'
            log_event('playwright_execution', status['error'], status='error', progress=16, details={'stderr_tail': install.stderr[-1000:]})
            _write_fallback_playwright_html('Playwright runtime preflight failed', status)
            return status
        log_event('playwright_execution', 'npm install completed successfully for generated-playwright.', status='done', progress=22)

    version = run_command(['npx', '--no-install', 'playwright', '--version'], cwd=GENERATED_PLAYWRIGHT_DIR, timeout=60)
    status['steps'].append({'name': 'playwright_cli_version', 'ok': version.ok, 'returncode': version.returncode, 'command': version.command, 'stdout': version.stdout[-1000:], 'stderr': version.stderr[-1000:], 'error': version.error})
    if not version.ok:
        status['error'] = 'Playwright CLI is still unavailable after dependency check. Run npm install in generated-playwright and retry.'
        log_event('playwright_execution', status['error'], status='error', progress=24, details={'stderr_tail': version.stderr[-1000:]})
        _write_fallback_playwright_html('Playwright runtime preflight failed', status)
        return status
    log_event('playwright_execution', f"Playwright CLI available: {(version.stdout or version.stderr).strip()}", status='done', progress=25)

    # Browser install is idempotent and normally quick when Chromium already exists.
    log_event('playwright_execution', 'Ensuring Chromium browser is installed for Playwright.', progress=27)
    browser = run_command(['npx', '--no-install', 'playwright', 'install', 'chromium'], cwd=GENERATED_PLAYWRIGHT_DIR, timeout=900)
    status['steps'].append({'name': 'playwright_install_chromium', 'ok': browser.ok, 'returncode': browser.returncode, 'command': browser.command, 'stdout': browser.stdout[-3000:], 'stderr': browser.stderr[-3000:], 'error': browser.error})
    status['chromium_install_ok_or_already_present'] = browser.ok
    log_event('playwright_execution', 'Chromium browser check completed.' if browser.ok else 'Chromium install command returned a warning; execution may still work if browser is already cached.', status='done' if browser.ok else 'warning', progress=30, details={'ok': browser.ok, 'stderr_tail': browser.stderr[-800:]})

    status['ok'] = True
    status['installed_after'] = _playwright_bin_exists()
    status['duration_seconds'] = round(time.time() - started, 2)
    return status



def _is_pipeline_fallback_report(index: Path) -> bool:
    """Detect fallback reports so stale fallbacks do not mask native Playwright reports."""
    try:
        if not index.exists():
            return False
        text = index.read_text(encoding='utf-8', errors='ignore')[:4000]
        return 'Playwright did not generate a native HTML report' in text or 'Fallback execution report' in text
    except Exception:
        return False


def _reset_playwright_html_report_dirs() -> dict[str, Any]:
    """Remove stale HTML report folders before a new execution.

    This is critical because an older fallback report at reports/html/index.html can
    otherwise make the GUI think the latest native Playwright report is ready, or can
    hide a new native report generated in playwright-report/.
    """
    removed: list[str] = []
    errors: list[str] = []
    dirs = [
        REPORTS_DIR / 'html',
        GENERATED_PLAYWRIGHT_DIR / 'playwright-report',
        GENERATED_PLAYWRIGHT_DIR / 'reports' / 'playwright-report',
        REPORTS_DIR / 'json-shards',
    ]
    for d in dirs:
        try:
            if d.exists():
                shutil.rmtree(d, ignore_errors=True)
                removed.append(str(d.relative_to(GENERATED_PLAYWRIGHT_DIR)))
        except Exception as exc:  # pragma: no cover - environment/filesystem specific
            errors.append(f'{d}: {type(exc).__name__}: {exc}')
    for f in [REPORTS_DIR / 'results.json']:
        try:
            if f.exists():
                f.unlink()
                removed.append(str(f.relative_to(GENERATED_PLAYWRIGHT_DIR)))
        except Exception as exc:
            errors.append(f'{f}: {type(exc).__name__}: {exc}')
    return {'removed': removed, 'errors': errors}


def _copy_default_html_report_if_present() -> dict[str, Any]:
    """Normalize the latest native Playwright HTML report to reports/html.

    The GUI always opens /artifacts/reports/html/index.html. This helper now
    avoids treating an old fallback page as a successful native Playwright report.
    """
    target_dir = REPORTS_DIR / 'html'
    target_index = target_dir / 'index.html'
    candidates = [
        GENERATED_PLAYWRIGHT_DIR / 'playwright-report' / 'index.html',
        GENERATED_PLAYWRIGHT_DIR / 'reports' / 'playwright-report' / 'index.html',
        target_index,
    ]
    inspected: list[str] = []
    for index in candidates:
        try:
            inspected.append(str(index.relative_to(GENERATED_PLAYWRIGHT_DIR)))
            if not index.exists():
                continue
            if _is_pipeline_fallback_report(index):
                # A fallback report is useful only as a last resort; it is not a native Playwright report.
                continue
            source_dir = index.parent
            if source_dir.resolve() == target_dir.resolve():
                return {
                    'ok': True,
                    'native': True,
                    'source': str(source_dir.relative_to(GENERATED_PLAYWRIGHT_DIR)),
                    'target': 'reports/html',
                    'copied': False,
                    'inspected': inspected,
                }
            if target_dir.exists():
                shutil.rmtree(target_dir, ignore_errors=True)
            shutil.copytree(source_dir, target_dir)
            return {
                'ok': True,
                'native': True,
                'source': str(source_dir.relative_to(GENERATED_PLAYWRIGHT_DIR)),
                'target': 'reports/html',
                'copied': True,
                'inspected': inspected,
            }
        except Exception as exc:  # pragma: no cover - Windows/filesystem specific
            return {'ok': False, 'native': False, 'error': f'{type(exc).__name__}: {exc}', 'target': 'reports/html', 'inspected': inspected}
    return {'ok': False, 'native': False, 'reason': 'No native Playwright HTML report index.html found.', 'target': 'reports/html', 'inspected': inspected}


def _run_playwright_streaming(
    args: list[str],
    env: dict[str, str],
    label: str,
    progress_start: int,
    progress_end: int,
    timeout_seconds: int | None = None,
) -> dict[str, Any]:
    """Run a Playwright command with plain-English runtime logs and bounded finalization."""
    resolved = resolve_command(args[0])
    command_display = ' '.join(args)
    stdout_lines: list[str] = []
    stderr_text = ''
    started = time.time()
    if not resolved:
        msg = f'{args[0]} not found; cannot launch Playwright.'
        log_event('playwright_execution', f'{label} failed before launch: {msg}', status='error', progress=progress_start, details={'command': command_display})
        return {'ok': False, 'returncode': None, 'command': command_display, 'cwd': str(GENERATED_PLAYWRIGHT_DIR), 'stdout': '', 'stderr': '', 'error': msg, 'duration_seconds': 0}

    final_args = [resolved, *args[1:]]
    log_event('playwright_execution', f'{label}: Playwright process started. Browser will launch in this step.', progress=progress_start, details={'command': command_display})
    try:
        proc = subprocess.Popen(
            final_args,
            cwd=str(GENERATED_PLAYWRIGHT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='utf-8',
            errors='replace',
            env=env,
            bufsize=1,
        )
        assert proc.stdout is not None
        last_log = 0.0
        deadline = time.time() + timeout_seconds if timeout_seconds else None
        for line in proc.stdout:
            line = line.rstrip('\n')
            if not line:
                if deadline and time.time() > deadline:
                    proc.kill()
                    stderr_text = f'{label} exceeded timeout of {timeout_seconds} seconds and was stopped.'
                    break
                continue
            stdout_lines.append(line)
            now = time.time()
            low = line.lower()
            if any(token in low for token in ['running ', 'passed', 'failed', 'timed out', 'error', 'retry', 'locator', 'expect', 'report', 'browser', 'worker']) or now - last_log > 8:
                last_log = now
                log_event('playwright_execution', f'{label}: {line[:500]}', progress=min(progress_end, progress_start + 4), details={'command_label': label})
            if deadline and now > deadline:
                proc.kill()
                stderr_text = f'{label} exceeded timeout of {timeout_seconds} seconds and was stopped.'
                break
        try:
            returncode = proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            proc.kill()
            returncode = proc.wait(timeout=10)
            stderr_text = stderr_text or f'{label} process exceeded timeout while closing and was killed.'
        duration = round(time.time() - started, 2)
        ok = returncode == 0
        log_event('playwright_execution', f"{label} {'passed' if ok else 'completed with issue'} in {duration}s.", status='done' if ok else 'warning', progress=progress_end, details={'returncode': returncode, 'duration_seconds': duration})
        return {
            'ok': ok,
            'returncode': returncode,
            'command': command_display,
            'cwd': str(GENERATED_PLAYWRIGHT_DIR),
            'stdout': '\n'.join(stdout_lines)[-20000:],
            'stderr': stderr_text[-8000:],
            'error': None,
            'duration_seconds': duration,
        }
    except Exception as exc:  # pragma: no cover - environment specific
        duration = round(time.time() - started, 2)
        log_event('playwright_execution', f'{label} crashed before completion: {type(exc).__name__}: {exc}', status='error', progress=progress_end, details={'duration_seconds': duration})
        return {
            'ok': False,
            'returncode': None,
            'command': command_display,
            'cwd': str(GENERATED_PLAYWRIGHT_DIR),
            'stdout': '\n'.join(stdout_lines)[-20000:],
            'stderr': stderr_text[-8000:],
            'error': f'{type(exc).__name__}: {exc}',
            'duration_seconds': duration,
        }


FAILED_TESTS_INVENTORY = REPORTS_DIR / 'failed-tests.json'
FAILED_ONLY_RERUN_REPORT = REPORTS_DIR / 'failed-only-rerun-report.json'
FAILED_ONLY_CONSOLIDATED_HTML = REPORTS_DIR / 'failed-only-consolidated-report.html'


def _normalise_spec_path(path_value: str) -> str:
    value = str(path_value or '').replace('\\', '/').strip()
    if not value:
        return ''
    if 'tests/generated/' in value:
        return value[value.index('tests/generated/'):]
    if value.endswith('.spec.ts') and '/' not in value:
        return f'tests/generated/{value}'
    return value


def _spec_to_feature(spec_path: str) -> str:
    name = Path(_normalise_spec_path(spec_path)).name
    if name.endswith('.spec.ts'):
        return name[:-8]
    return Path(name).stem


def _read_playwright_results_json() -> dict[str, Any]:
    """Read Playwright JSON results from sequential or distributed runs.

    Sequential execution writes reports/results.json. Distributed execution writes one
    JSON result per shard under reports/json-shards/. Aggregating shard JSON prevents
    the RCA engine from treating every selected spec as failed when only one shard/spec
    actually failed.
    """
    single_candidates = [
        REPORTS_DIR / 'results.json',
        GENERATED_PLAYWRIGHT_DIR / 'reports' / 'results.json',
        GENERATED_PLAYWRIGHT_DIR / 'test-results' / 'results.json',
    ]
    for c in single_candidates:
        if c.exists():
            try:
                return {'ok': True, 'path': str(c.relative_to(REPO_ROOT)), 'data': json.loads(c.read_text(encoding='utf-8', errors='replace')), 'mode': 'single'}
            except Exception as exc:
                return {'ok': False, 'path': str(c), 'error': f'{type(exc).__name__}: {exc}', 'data': {}}

    shard_dir = REPORTS_DIR / 'json-shards'
    shard_files = sorted(shard_dir.glob('*.json')) if shard_dir.exists() else []
    if shard_files:
        merged = {'config': {}, 'suites': [], 'errors': [], 'stats': {}}
        parsed_files: list[str] = []
        errors: list[str] = []
        for f in shard_files:
            try:
                data = json.loads(f.read_text(encoding='utf-8', errors='replace'))
                parsed_files.append(str(f.relative_to(REPO_ROOT)))
                if not merged.get('config') and data.get('config'):
                    merged['config'] = data.get('config')
                merged['suites'].extend(data.get('suites') or [])
                merged['errors'].extend(data.get('errors') or [])
            except Exception as exc:
                errors.append(f'{f}: {type(exc).__name__}: {exc}')
        return {'ok': bool(parsed_files), 'path': str(shard_dir.relative_to(REPO_ROOT)), 'files': parsed_files, 'errors': errors, 'data': merged, 'mode': 'shards'}
    return {'ok': False, 'error': 'No Playwright JSON results file found.', 'data': {}}


def _extract_failed_from_playwright_json(data: dict[str, Any]) -> dict[str, Any]:
    failed_tests: list[dict[str, Any]] = []
    all_specs: set[str] = set()
    spec_statuses: dict[str, dict[str, Any]] = {}

    def final_status_for(statuses: list[str], failed: bool) -> str:
        unique = [s for s in dict.fromkeys([str(x).lower() for x in statuses if x]) if s]
        if failed:
            return 'failed'
        if any(s in {'passed', 'expected'} for s in unique):
            return 'passed'
        if any(s == 'skipped' for s in unique):
            return 'skipped'
        return unique[-1] if unique else 'unknown'

    def visit_suite(suite: dict[str, Any], inherited_file: str = '') -> None:
        suite_file = suite.get('file') or inherited_file
        for spec in suite.get('specs') or []:
            spec_file = _normalise_spec_path(spec.get('file') or suite_file or '')
            if spec_file:
                all_specs.add(spec_file)
            title = spec.get('title') or ''
            failed = False
            statuses: list[str] = []
            for test in spec.get('tests') or []:
                status = str(test.get('status') or '').lower()
                if status:
                    statuses.append(status)
                if status and status not in {'expected', 'passed', 'skipped'}:
                    failed = True
                for result in test.get('results') or []:
                    rstatus = str(result.get('status') or '').lower()
                    if rstatus:
                        statuses.append(rstatus)
                    if rstatus in {'failed', 'timedout', 'timed out', 'interrupted'}:
                        failed = True
            if spec_file:
                current = spec_statuses.get(spec_file, {'spec': spec_file, 'feature': _spec_to_feature(spec_file), 'titles': [], 'statuses': [], 'status': 'unknown'})
                current['titles'].append(title)
                current['statuses'].extend(statuses)
                # If any spec in the file failed, keep file-level status failed.
                current_failed = failed or current.get('status') == 'failed'
                current['status'] = final_status_for(current['statuses'], current_failed)
                spec_statuses[spec_file] = current
            if failed:
                failed_tests.append({
                    'spec': spec_file,
                    'feature': _spec_to_feature(spec_file),
                    'title': title,
                    'statuses': list(dict.fromkeys(statuses)),
                })
        for child in suite.get('suites') or []:
            visit_suite(child, suite_file)

    for suite in data.get('suites') or []:
        visit_suite(suite)

    failed_specs = sorted({t['spec'] for t in failed_tests if t.get('spec')})
    passed_specs = sorted([s for s, row in spec_statuses.items() if row.get('status') == 'passed' and s not in failed_specs])
    return {
        'ok': True,
        'all_specs': sorted(all_specs),
        'spec_statuses': spec_statuses,
        'passed_specs': passed_specs,
        'failed_specs': failed_specs,
        'failed_features': [_spec_to_feature(s) for s in failed_specs],
        'failed_tests': failed_tests,
        'failed_count': len(failed_tests),
    }


def _extract_failed_specs_from_stdout(stdout: str, target_args: list[str]) -> list[str]:
    text = str(stdout or '')
    found = set(_normalise_spec_path(m.group(1)) for m in re.finditer(r'(tests[\\/]generated[\\/][\w.\-]+\.spec\.ts)', text))
    return sorted([f for f in found if f]) or list(target_args)


def _write_failed_test_inventory(*, execution_report: dict[str, Any], target_args: list[str], execution_mode: str, source: str = 'latest_execution') -> dict[str, Any]:
    """Persist failed specs so RCA/self-healing can rerun only the affected scripts.

    Playwright's native HTML report is still the primary human report. This JSON file is the
    automation hand-off between execution -> RCA -> patch -> failed-only rerun.
    """
    results_json = _read_playwright_results_json()
    parsed = _extract_failed_from_playwright_json(results_json.get('data') or {}) if results_json.get('data') else {'failed_specs': [], 'failed_features': [], 'failed_tests': [], 'all_specs': [], 'passed_specs': [], 'spec_statuses': {}}
    failed_specs = parsed.get('failed_specs') or []
    stdout_chunks: list[str] = []
    if execution_report.get('result'):
        stdout_chunks.append(str(execution_report.get('result', {}).get('stdout', '')))
    for r in execution_report.get('results') or []:
        if not r.get('ok'):
            stdout_chunks.append(str(r.get('stdout', '')) + '\n' + str(r.get('stderr', '')))
    extraction_note = ''
    if not failed_specs and not execution_report.get('ok'):
        # Try stdout extraction, but never mark every selected target as failed just because
        # Playwright JSON was unavailable. That caused RCA to analyze and rerun already-passed scripts.
        extracted = _extract_failed_specs_from_stdout('\n'.join(stdout_chunks), [])
        failed_specs = extracted
        if not failed_specs:
            extraction_note = 'Playwright execution failed but no exact failed spec could be extracted. RCA is blocked until a JSON report or exact failed spec is available; the pipeline will not assume all selected specs failed.'
    failed_specs = sorted(dict.fromkeys(_normalise_spec_path(s) for s in failed_specs if _normalise_spec_path(s)))
    inventory = {
        'ok': True,
        'source': source,
        'execution_mode': execution_mode,
        'generated_at_epoch_ms': int(time.time() * 1000),
        'target_args': target_args,
        'all_specs': parsed.get('all_specs') or target_args,
        'passed_specs': parsed.get('passed_specs') or [s for s in (parsed.get('all_specs') or target_args) if _normalise_spec_path(s) not in failed_specs],
        'spec_statuses': parsed.get('spec_statuses') or {},
        'failed_specs': failed_specs,
        'failed_features': [_spec_to_feature(s) for s in failed_specs],
        'failed_tests': parsed.get('failed_tests') or [],
        'failed_count': len(failed_specs),
        'results_json': {k: v for k, v in results_json.items() if k != 'data'},
        'native_html_report': 'generated-playwright/reports/html/index.html',
        'note': 'RCA/self-healing rerun uses failed_specs only. The pipeline never assumes all selected specs failed when JSON parsing is unavailable.',
        'extraction_note': extraction_note,
    }
    FAILED_TESTS_INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    FAILED_TESTS_INVENTORY.write_text(json.dumps(inventory, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    if failed_specs:
        log_event('playwright_execution', f'Failed-only rerun inventory recorded: {len(failed_specs)} failed spec(s) will be targeted after RCA/self-healing.', status='warning', progress=100, details={'failed_specs': failed_specs})
    elif not execution_report.get('ok'):
        log_event('playwright_execution', 'Execution failed, but no exact failed spec inventory could be built. RCA will request a rerun with JSON reporting instead of analyzing all scripts.', status='error', progress=100, details={'target_args': target_args, 'results_json': inventory.get('results_json'), 'extraction_note': extraction_note})
    else:
        log_event('playwright_execution', 'Failed-only rerun inventory recorded: no failed specs detected.', status='done', progress=100, details={'target_args': target_args})
    return inventory


def read_failed_test_inventory() -> dict[str, Any]:
    if not FAILED_TESTS_INVENTORY.exists():
        return {'ok': False, 'error': 'No failed-test inventory found. Run a generated Playwright execution first.'}
    try:
        data = json.loads(FAILED_TESTS_INVENTORY.read_text(encoding='utf-8', errors='replace'))
        data['ok'] = True
        return data
    except Exception as exc:
        return {'ok': False, 'error': f'{type(exc).__name__}: {exc}', 'path': str(FAILED_TESTS_INVENTORY)}


def _archive_current_html_report(label: str) -> dict[str, Any]:
    src = REPORTS_DIR / 'html'
    if not (src / 'index.html').exists():
        return {'ok': False, 'reason': 'No current native/fallback Playwright HTML report found to archive.'}
    dest = REPORTS_DIR / label
    try:
        if dest.exists():
            shutil.rmtree(dest, ignore_errors=True)
        shutil.copytree(src, dest)
        return {'ok': True, 'source': str(src.relative_to(REPO_ROOT)), 'target': str(dest.relative_to(REPO_ROOT)), 'url': f'/artifacts/reports/{label}/index.html'}
    except Exception as exc:
        return {'ok': False, 'error': f'{type(exc).__name__}: {exc}'}


def _html_escape(value: Any) -> str:
    return str(value if value is not None else '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def _write_failed_only_consolidated_report(payload: dict[str, Any]) -> Path:
    """Write a complete RCA rerun report that preserves original passed results.

    Native Playwright HTML can only represent the latest execution scope. After a failed-only rerun,
    that native report correctly shows only the rerun specs. This consolidated report provides the
    enterprise-level full picture: originally passed specs remain passed, failed specs are updated
    with the failed-only rerun result, and links to both native reports are retained.
    """
    full_url = payload.get('archived_full_report', {}).get('url') or ''
    rerun_url = '/artifacts/reports/html/index.html'
    original = payload.get('failed_inventory') or {}
    rerun_inventory = payload.get('rerun_failed_inventory') or {}
    original_all = [_normalise_spec_path(s) for s in (original.get('all_specs') or original.get('target_args') or []) if _normalise_spec_path(s)]
    original_failed = set(_normalise_spec_path(s) for s in (original.get('failed_specs') or []) if _normalise_spec_path(s))
    rerun_failed = set(_normalise_spec_path(s) for s in (rerun_inventory.get('failed_specs') or []) if _normalise_spec_path(s))
    rerun_all = set(_normalise_spec_path(s) for s in (rerun_inventory.get('all_specs') or original.get('failed_specs') or []) if _normalise_spec_path(s))
    all_specs = list(dict.fromkeys(original_all + sorted(original_failed)))
    rows = []
    passed_after_patch = 0
    still_failed = 0
    originally_passed = 0
    for idx, spec in enumerate(all_specs, 1):
        feature = _spec_to_feature(spec)
        if spec in original_failed:
            if spec in rerun_failed:
                status = 'Still failing after RCA patch'
                cls = 'bad'
                still_failed += 1
            elif spec in rerun_all:
                status = 'Passed after RCA patch'
                cls = 'ok'
                passed_after_patch += 1
            else:
                status = 'Was failed originally; rerun status unavailable'
                cls = 'warn'
        else:
            status = 'Passed in original full run; not rerun to save time'
            cls = 'ok'
            originally_passed += 1
        rows.append(f"<tr><td>{idx}</td><td><code>{_html_escape(spec)}</code></td><td>{_html_escape(feature)}</td><td class='{cls}'>{_html_escape(status)}</td></tr>")
    if not rows:
        rows.append('<tr><td colspan="4">No spec-level result rows were available. Open the native Playwright reports for details.</td></tr>')
    rerun_ok = payload.get('rerun', {}).get('ok')
    final_status = 'PASSED AFTER RCA PATCH' if rerun_ok and not still_failed else ('COMPLETED WITH ISSUE' if original_failed else 'NO FAILURES TO RERUN')
    html = f"""<!doctype html><html><head><meta charset='utf-8'/><title>Complete RCA Failed-Only Rerun Report</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;margin:24px;background:#f8fafc;color:#0f172a}}
.card{{background:white;border:1px solid #dbe3ef;border-radius:14px;padding:16px;margin:14px 0;box-shadow:0 1px 2px #0001}}
.ok{{color:#16a34a;font-weight:800}}.bad{{color:#dc2626;font-weight:800}}.warn{{color:#b45309;font-weight:800}}
table{{border-collapse:collapse;width:100%;background:white}}td,th{{border-bottom:1px solid #e2e8f0;padding:8px;text-align:left;vertical-align:top}}
code{{background:#0f172a;color:#dbeafe;padding:3px 6px;border-radius:6px}}pre{{white-space:pre-wrap;background:#0f172a;color:#dbeafe;border-radius:10px;padding:14px;overflow:auto}}
</style></head><body>
<h1>Complete RCA Failed-Only Rerun Report</h1>
<div class='card'><b>Final status:</b> <span class='{ 'ok' if rerun_ok and not still_failed else 'bad' }'>{_html_escape(final_status)}</span>
<p>After RCA/self-healing, the pipeline re-executed only the specs that failed in the previous full run. Passed specs from the original full run were preserved to avoid unnecessary reruns.</p></div>
<div class='card'><h2>Summary</h2><ul>
<li>Originally passed and preserved: <b>{originally_passed}</b></li>
<li>Originally failed and passed after RCA patch: <b>{passed_after_patch}</b></li>
<li>Still failing after RCA patch: <b>{still_failed}</b></li>
<li>Failed-only rerun scope: <b>{len(original_failed)}</b> spec(s)</li>
</ul></div>
<div class='card'><h2>Reports</h2><ul>
<li><a href='{rerun_url}'>Open native Playwright report for failed-only rerun</a></li>
{f"<li><a href='{full_url}'>Open archived full-run native Playwright report from before RCA patch</a></li>" if full_url else ''}
</ul><p><b>Note:</b> Native Playwright HTML shows the latest execution scope. This consolidated report gives the complete run picture without re-running already-passed scripts.</p></div>
<div class='card'><h2>Complete Spec Result Matrix</h2><table><tr><th>#</th><th>Spec</th><th>Feature</th><th>Status</th></tr>{''.join(rows)}</table></div>
<div class='card'><h2>Raw payload</h2><pre>{_html_escape(json.dumps(payload, indent=2, ensure_ascii=False))}</pre></div>
</body></html>"""
    FAILED_ONLY_CONSOLIDATED_HTML.write_text(html, encoding='utf-8')
    return FAILED_ONLY_CONSOLIDATED_HTML


def execute_failed_only_after_healing(
    project: str = 'chromium',
    use_mcp: bool = True,
    headed: bool = False,
    base_url: str = '',
    execution_mode: str = 'sequential',
    shards: int = 2,
) -> dict[str, Any]:
    """Re-execute only specs that failed in the previous execution after RCA/self-healing patch.

    This saves time by avoiding a full-suite rerun. The previous full-run report is archived first;
    reports/html is then updated with the native Playwright report from the failed-only rerun.
    """
    inventory = read_failed_test_inventory()
    if not inventory.get('ok'):
        log_event('playwright_execution', 'Failed-only rerun blocked: no failed-test inventory exists.', status='error', progress=5, details=inventory)
        return inventory
    failed_features = [f for f in (inventory.get('failed_features') or []) if f]
    if not failed_features:
        msg = 'No failed specs found in failed-test inventory. Full rerun is not required.'
        log_event('playwright_execution', msg, status='done', progress=100, details=inventory)
        return {'ok': True, 'skipped': True, 'message': msg, 'failed_inventory': inventory}
    archive = _archive_current_html_report('full-run-before-failed-only-rerun')
    log_event('playwright_execution', f'Failed-only rerun will execute {len(failed_features)} failed spec(s) only after RCA/self-healing.', progress=12, details={'failed_features': failed_features, 'archive': archive})
    mode = (execution_mode or 'sequential').strip().lower()
    safe_shards = max(1, min(int(shards or 1), 20))
    if mode == 'distributed' and len(failed_features) > 1:
        rerun = execute_feature_distributed(feature='failed_only', features=failed_features, project=project, use_mcp=use_mcp, headed=headed, base_url=base_url, shards=min(safe_shards, len(failed_features)))
    else:
        rerun = execute_feature_sequential(feature='failed_only', features=failed_features, project=project, use_mcp=use_mcp, headed=headed, base_url=base_url)
    # execute_feature_* writes failed-tests.json for the rerun scope. Capture it before returning
    # so the consolidated report can combine original passed specs with updated failed-spec status.
    rerun_inventory = read_failed_test_inventory()
    payload = {
        'ok': bool(rerun.get('ok')),
        'stage': 'failed_only_rerun_completed',
        'scope': 'failed_specs_only',
        'failed_inventory': inventory,
        'rerun_failed_inventory': rerun_inventory,
        'archived_full_report': archive,
        'rerun': rerun,
        'playwright_html_report_url': '/artifacts/reports/html/index.html',
        'archived_full_report_url': archive.get('url') if isinstance(archive, dict) else None,
        'message': 'Failed-only rerun completed. Native Playwright shows the rerun scope. The consolidated report preserves the original passed tests and updates failed tests with rerun status.',
    }
    FAILED_ONLY_RERUN_REPORT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    consolidated = _write_failed_only_consolidated_report(payload)
    payload['failed_only_consolidated_report'] = str(consolidated.relative_to(REPO_ROOT))
    payload['failed_only_consolidated_report_url'] = '/artifacts/reports/failed-only-consolidated-report.html'
    log_event('playwright_execution', 'Failed-only rerun report is ready. Open native rerun report or consolidated RCA rerun summary.', status='done' if payload['ok'] else 'warning', progress=100, details={'ok': payload['ok'], 'failed_features': failed_features})
    return payload


def execute_feature_sequential(
    feature: str = 'login',
    project: str = 'chromium',
    use_mcp: bool = True,
    headed: bool = False,
    base_url: str = '',
    features: list[str] | None = None,
) -> dict[str, Any]:
    """Run selected generated specs sequentially in a single Playwright process.

    This is the safest default for headed debugging because it avoids multiple simultaneous browser
    windows and avoids the distributed merge step that can make the GUI appear stuck on some Windows machines.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    feature = (feature or 'all').strip().lower()
    clean_features = [str(f).strip().lower() for f in (features or []) if str(f).strip()]
    target_args = _target_args(feature, clean_features)
    log_event('playwright_execution', f'Execution plan prepared: sequential mode, {len(target_args)} selected spec target(s), {"headed" if headed else "headless"} mode.', progress=8, details={'feature': feature, 'features': clean_features, 'target_args': target_args, 'headed': headed})

    missing: list[str] = []
    if clean_features:
        for f in clean_features:
            spec = GENERATED_PLAYWRIGHT_DIR / 'tests' / 'generated' / f'{f}.spec.ts'
            if not spec.exists():
                missing.append(str(spec))
    elif feature not in {'all', '*', 'suite'}:
        target = GENERATED_PLAYWRIGHT_DIR / _feature_spec_arg(feature)
        if not target.exists():
            missing.append(str(target))
    elif not (GENERATED_PLAYWRIGHT_DIR / 'tests' / 'generated').exists():
        missing.append(str(GENERATED_PLAYWRIGHT_DIR / 'tests' / 'generated'))
    if missing:
        report = {'ok': False, 'error': 'Generated spec(s) not found for sequential execution.', 'missing_specs': missing, 'target_args': target_args}
        log_event('playwright_execution', 'Sequential execution blocked: one or more generated spec files are missing.', status='error', progress=10, details=report)
        _write_fallback_playwright_html('Playwright execution precheck failed', report)
        return report

    runtime = ensure_playwright_runtime(auto_install=True)
    if not runtime.get('ok'):
        log_event('playwright_execution', 'Sequential execution stopped because Playwright runtime preflight failed.', status='error', progress=100, details={'error': runtime.get('error')})
        return {'ok': False, 'stage': 'playwright_runtime_preflight_failed', 'runtime_preflight': runtime, 'error': runtime.get('error', 'Playwright runtime preflight failed.')}

    report_reset = _reset_playwright_html_report_dirs()
    log_event('playwright_execution', 'Cleared stale Playwright HTML report folders before sequential execution.', progress=31, details=report_reset)
    effective_base_url = normalize_base_url(base_url or load_project_config().get('base_url', ''))
    mcp = mcp_status(headless=not headed) if use_mcp else {'enabled': False}
    env = {**os.environ.copy(), 'PW_WORKERS': '1', 'PLAYWRIGHT_HTML_OPEN': 'never', 'PLAYWRIGHT_HTML_OUTPUT_DIR': 'reports/html', 'PLAYWRIGHT_JSON_OUTPUT_NAME': 'reports/results.json'}
    if effective_base_url:
        env['BASE_URL'] = effective_base_url
        env['TEST_BASE_URL'] = effective_base_url
    args = [
        'npx', '--no-install', 'playwright', 'test',
        *target_args,
        f'--project={project}',
        '--workers=1',
        '--reporter=line,json,html',
    ]
    if headed:
        args.append('--headed')
    log_event('playwright_execution', 'Starting sequential Playwright execution. This mode runs one browser flow at a time and is recommended for headed debugging.', progress=34, details={'target_args': target_args})
    result = _run_playwright_streaming(args, env, 'Sequential execution', 36, 92, timeout_seconds=None)
    html_copy = _copy_default_html_report_if_present()
    html_ready = (REPORTS_DIR / 'html' / 'index.html').exists()
    report = {
        'ok': bool(result.get('ok')),
        'mode': 'headed' if headed else 'headless',
        'execution_mode': 'local_sequential_single_process',
        'feature': feature,
        'features': clean_features,
        'target_args': target_args,
        'project': project,
        'base_url': effective_base_url,
        'runtime_preflight': runtime,
        'report_reset': report_reset,
        'result': result,
        'mcp': mcp,
        'html_report_ready': html_ready,
        'html_report_normalization': html_copy,
        'message': 'Sequential execution completed. This mode avoids distributed shard merge delays and is best for headed demo/debugging.' if result.get('ok') else 'Sequential execution completed with issue. Check stdout/stderr in the runtime logs and report.',
    }
    if not html_ready:
        # Preserve native Playwright HTML whenever it exists, even when tests fail.
        # Test failures are valuable inside the native Playwright report with traces/screenshots.
        _write_fallback_playwright_html('Playwright sequential execution report missing', report)
    inventory = _write_failed_test_inventory(execution_report=report, target_args=target_args, execution_mode='sequential', source='sequential_execution')
    report['failed_test_inventory'] = inventory
    out = REPORTS_DIR / 'sequential-execution-report.json'
    out.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    log_event('playwright_execution', 'Sequential Playwright execution finished. Report is ready.', status='done' if result.get('ok') else 'warning', progress=100, details={'ok': result.get('ok'), 'report': str(out.relative_to(REPO_ROOT)), 'html_report': 'generated-playwright/reports/html/index.html'})
    return report

def _run_one_shard(target_args: list[str], idx: int, total: int, project: str, headed: bool, base_url: str) -> dict[str, Any]:
    """Run one Playwright shard while streaming readable log lines into runtime events."""
    shard_name = f'{idx}/{total}'
    shard_out = REPORTS_DIR / 'blob-shards' / f'shard-{idx}'
    shard_out.mkdir(parents=True, exist_ok=True)
    args = [
        'npx', '--no-install', 'playwright', 'test',
        *target_args,
        f'--project={project}',
        f'--shard={idx}/{total}',
        f'--output=test-results/shard-{idx}',
        '--reporter=blob,line,json',
    ]
    if headed:
        args.append('--headed')
    json_out_dir = REPORTS_DIR / 'json-shards'
    json_out_dir.mkdir(parents=True, exist_ok=True)
    env = {**os.environ.copy(), 'PW_WORKERS': '1', 'PLAYWRIGHT_BLOB_OUTPUT_DIR': str(shard_out), 'PLAYWRIGHT_HTML_OPEN': 'never', 'PLAYWRIGHT_JSON_OUTPUT_NAME': str(json_out_dir / f'shard-{idx}-results.json')}
    if base_url:
        env['BASE_URL'] = base_url
        env['TEST_BASE_URL'] = base_url

    resolved = resolve_command(args[0])
    command_display = ' '.join(args)
    if not resolved:
        msg = 'npx not found; cannot launch Playwright shard.'
        log_event('playwright_execution', f'Shard {shard_name} failed before launch: {msg}', status='error', progress=32, details={'command': command_display})
        return {'shard': shard_name, 'ok': False, 'returncode': None, 'command': command_display, 'cwd': str(GENERATED_PLAYWRIGHT_DIR), 'blob_output_dir': str(shard_out.relative_to(REPO_ROOT)), 'stdout': '', 'stderr': '', 'error': msg}

    final_args = [resolved, *args[1:]]
    log_event('playwright_execution', f'Starting shard {shard_name}: browser will launch in {"headed" if headed else "headless"} mode.', progress=32, details={'command': command_display, 'spec_count': len(target_args)})
    stdout_lines: list[str] = []
    stderr_text = ''
    started = time.time()
    try:
        proc = subprocess.Popen(
            final_args,
            cwd=str(GENERATED_PLAYWRIGHT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='utf-8',
            errors='replace',
            env=env,
            bufsize=1,
        )
        assert proc.stdout is not None
        last_log = 0.0
        for line in proc.stdout:
            line = line.rstrip('\n')
            if not line:
                continue
            stdout_lines.append(line)
            # Do not flood JSONL. Log useful Playwright line-reporter output and periodic heartbeat.
            now = time.time()
            low = line.lower()
            if any(token in low for token in ['running ', 'passed', 'failed', 'timed out', 'error', 'retry', 'locator', 'expect']) or now - last_log > 8:
                last_log = now
                log_event('playwright_execution', f'Shard {shard_name}: {line[:500]}', progress=min(88, 34 + int((idx / max(total, 1)) * 45)), details={'shard': shard_name})
        try:
            returncode = proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            returncode = proc.wait(timeout=10)
            stderr_text = 'Shard process exceeded timeout while closing and was killed.'
        ok = returncode == 0
        duration = round(time.time() - started, 2)
        log_event('playwright_execution', f"Shard {shard_name} {'passed' if ok else 'completed with issue'} in {duration}s.", status='done' if ok else 'warning', progress=min(90, 38 + int((idx / max(total, 1)) * 45)), details={'shard': shard_name, 'returncode': returncode, 'duration_seconds': duration})
        stdout = '\n'.join(stdout_lines)
        return {
            'shard': shard_name,
            'ok': ok,
            'returncode': returncode,
            'command': command_display,
            'cwd': str(GENERATED_PLAYWRIGHT_DIR),
            'blob_output_dir': str(shard_out.relative_to(REPO_ROOT)),
            'stdout': stdout[-16000:],
            'stderr': stderr_text[-8000:],
            'error': None,
            'duration_seconds': duration,
        }
    except Exception as exc:  # pragma: no cover - environment specific
        duration = round(time.time() - started, 2)
        log_event('playwright_execution', f'Shard {shard_name} crashed before completion: {type(exc).__name__}: {exc}', status='error', progress=50, details={'shard': shard_name})
        return {
            'shard': shard_name,
            'ok': False,
            'returncode': None,
            'command': command_display,
            'cwd': str(GENERATED_PLAYWRIGHT_DIR),
            'blob_output_dir': str(shard_out.relative_to(REPO_ROOT)),
            'stdout': '\n'.join(stdout_lines)[-16000:],
            'stderr': stderr_text[-8000:],
            'error': f'{type(exc).__name__}: {exc}',
            'duration_seconds': duration,
        }


def _merge_blob_reports() -> dict[str, Any]:
    blob_root = REPORTS_DIR / 'blob-shards'
    merged_input = REPORTS_DIR / 'blob-merge-input'
    if merged_input.exists():
        shutil.rmtree(merged_input, ignore_errors=True)
    merged_input.mkdir(parents=True, exist_ok=True)
    count = 0
    for zip_file in blob_root.glob('**/*.zip'):
        target = merged_input / f'{zip_file.parent.name}-{zip_file.name}'
        shutil.copy2(zip_file, target)
        count += 1
    if count == 0:
        result = {'ok': False, 'reason': 'No blob report zip files found to merge. This usually means Playwright did not start, npm dependencies are missing, or all shards failed before test discovery.', 'blob_root': str(blob_root.relative_to(REPO_ROOT))}
        log_event('playwright_execution', 'No blob report zip files found to merge; native report cannot be created.', status='warning', progress=92, details=result)
        _write_fallback_playwright_html('Playwright distributed execution did not start', result)
        return result
    log_event('playwright_execution', f'Merging {count} Playwright blob report file(s) into one HTML report.', progress=94, details={'blob_count': count})
    proc = run_command(['npx', '--no-install', 'playwright', 'merge-reports', '--reporter', 'html', str(merged_input)], cwd=GENERATED_PLAYWRIGHT_DIR, timeout=90, extra_env={'PLAYWRIGHT_HTML_OPEN': 'never', 'PLAYWRIGHT_HTML_OUTPUT_DIR': 'reports/html'})
    html_copy = _copy_default_html_report_if_present()
    html_ready = (REPORTS_DIR / 'html' / 'index.html').exists()
    log_event('playwright_execution', 'Playwright HTML merge completed and report is ready.' if html_ready else 'Playwright HTML merge completed with issue; fallback report will be created.', status='done' if html_ready else 'warning', progress=97, details={'ok': proc.ok, 'html_ready': html_ready, 'stderr_tail': proc.stderr[-1000:]})
    return {'ok': bool(proc.ok and html_ready), 'count': count, 'command': proc.command, 'cwd': str(GENERATED_PLAYWRIGHT_DIR), 'stdout': proc.stdout[-5000:], 'stderr': proc.stderr[-5000:], 'error': proc.error, 'html_report': 'generated-playwright/reports/html/index.html', 'html_report_ready': html_ready, 'html_report_normalization': html_copy}


def execute_feature_distributed(
    feature: str = 'login',
    project: str = 'chromium',
    use_mcp: bool = True,
    headed: bool = False,
    base_url: str = '',
    shards: int = 5,
    features: list[str] | None = None,
) -> dict[str, Any]:
    """Run selected specs in shard groups and merge into one Playwright HTML report."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    feature = (feature or 'all').strip().lower()
    clean_features = [str(f).strip().lower() for f in (features or []) if str(f).strip()]
    target_args = _target_args(feature, clean_features)
    shards = max(1, min(int(shards or 1), 20))
    log_event('playwright_execution', f'Execution plan prepared: {len(target_args)} selected spec target(s), {shards} shard(s), {"headed" if headed else "headless"} mode.', progress=8, details={'feature': feature, 'features': clean_features, 'target_args': target_args, 'shards': shards, 'headed': headed})

    missing: list[str] = []
    if clean_features:
        for f in clean_features:
            spec = GENERATED_PLAYWRIGHT_DIR / 'tests' / 'generated' / f'{f}.spec.ts'
            if not spec.exists():
                missing.append(str(spec))
    elif feature not in {'all', '*', 'suite'}:
        target = GENERATED_PLAYWRIGHT_DIR / _feature_spec_arg(feature)
        if not target.exists():
            missing.append(str(target))
    elif not (GENERATED_PLAYWRIGHT_DIR / 'tests' / 'generated').exists():
        return {'ok': False, 'error': 'tests/generated directory not found.'}
    if missing:
        report = {'ok': False, 'error': 'Generated spec(s) not found for distributed execution.', 'missing_specs': missing, 'target_args': target_args}
        log_event('playwright_execution', 'Execution blocked: one or more generated spec files are missing.', status='error', progress=10, details=report)
        _write_fallback_playwright_html('Playwright execution precheck failed', report)
        return report

    runtime = ensure_playwright_runtime(auto_install=True)
    if not runtime.get('ok'):
        log_event('playwright_execution', 'Execution stopped because Playwright runtime preflight failed.', status='error', progress=100, details={'error': runtime.get('error')})
        return {'ok': False, 'stage': 'playwright_runtime_preflight_failed', 'runtime_preflight': runtime, 'error': runtime.get('error', 'Playwright runtime preflight failed.')}

    report_reset = _reset_playwright_html_report_dirs()
    log_event('playwright_execution', 'Cleared stale Playwright HTML report folders before distributed execution.', progress=31, details=report_reset)
    effective_base_url = normalize_base_url(base_url or load_project_config().get('base_url', ''))
    mcp = mcp_status(headless=not headed) if use_mcp else {'enabled': False}
    blob_root = REPORTS_DIR / 'blob-shards'
    if blob_root.exists():
        shutil.rmtree(blob_root, ignore_errors=True)
    results: list[dict[str, Any]] = []
    log_event('playwright_execution', f'Starting {shards} shard worker(s). Progress will update as each shard prints output and finishes.', progress=32, details={'shards': shards, 'target_args': target_args})
    with ThreadPoolExecutor(max_workers=shards) as pool:
        future_map = {pool.submit(_run_one_shard, target_args, i, shards, project, headed, effective_base_url): i for i in range(1, shards + 1)}
        completed = 0
        for future in as_completed(future_map):
            result = future.result()
            results.append(result)
            completed += 1
            pct = min(91, 38 + int((completed / max(shards, 1)) * 50))
            log_event('playwright_execution', f'Shard progress: {completed}/{shards} shard(s) finished.', progress=pct, status='done' if result.get('ok') else 'warning', details={'completed': completed, 'shards': shards, 'last_shard': result.get('shard'), 'ok': result.get('ok')})
    results = sorted(results, key=lambda r: r.get('shard', ''))
    merge = _merge_blob_reports()
    ok = all(r.get('ok') for r in results) and bool(merge.get('ok'))
    report = {
        'ok': ok,
        'mode': 'headed' if headed else 'headless',
        'execution_mode': 'local_sharded_parallel_with_merged_report',
        'feature': feature,
        'features': clean_features,
        'target_args': target_args,
        'project': project,
        'shards': shards,
        'tests_per_shard_model': 'Playwright distributes the selected test files across shards; for 100 tests and 5 shards this is roughly 20 tests per shard.',
        'base_url': effective_base_url,
        'runtime_preflight': runtime,
        'report_reset': report_reset,
        'results': results,
        'merge': merge,
        'mcp': mcp,
        'message': 'Distributed execution completed using Playwright --shard and merged blob reports into one HTML report.' if ok else 'Distributed execution did not complete successfully. Check runtime_preflight and shard stderr/stdout for the root cause.',
    }
    if not merge.get('html_report_ready'):
        # Preserve native Playwright HTML whenever merge produced it, even if some tests failed.
        _write_fallback_playwright_html('Playwright distributed execution report missing', report)
    inventory = _write_failed_test_inventory(execution_report=report, target_args=target_args, execution_mode='distributed', source='distributed_execution')
    report['failed_test_inventory'] = inventory
    out = REPORTS_DIR / 'distributed-execution-report.json'
    out.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    log_event('playwright_execution', 'Distributed Playwright execution finished. Native/fallback report is ready.', status='done' if ok else 'warning', progress=100, details={'ok': ok, 'report': str(out.relative_to(REPO_ROOT)), 'html_report': 'generated-playwright/reports/html/index.html'})
    return report
